name: Deploy React App to EC2

on:
  push:
    branches:
      - main  # or 'master' if that's your default

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: 3.111.146.115
        username: ec2-user
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          cd biogram-frontend
          git pull origin main
          npm install
          npm run build
          sudo systemctl restart nginx